name: node.js CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@4.2.2
      - name: Setup node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 18
      - name: Run install
        run: npm install
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: Deploy the application
        run: npm run deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  # <-- end of build job encapsulation -->
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkour code
        uses: actions/checkout@4.2.2
      - name: Setup node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 18
      - name: Run install
        run: npm install
      - name: Install dependencies
        run: npm ci
      - name: Install Jest
        run: npm install --save-dev jest
      - name: Run Test
        run: npm test -- --passWithNoTests
# <-- end of test job encapsulation -->
        
