name: node.js CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@4
      - name: Setup node.js
        uses: actions/setup-node@4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
  # <-- end of build job encapsulation -->
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkour code
        uses: actions/checkout@4
      - name: Setup node.js
        uses: actions/setup-node@4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Test
        run: npm test
# <-- end of test job encapsulation -->
        
