name: Data Passing Workfflow
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Generate Data
      run: echo "Some data generated in job 1" > data.txt
    - name: Upload data as artifactor
      uses: actions/upload-artifact@v4.6.2
      with:
        name: data-artifact
        path: data.txt
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Download data artifact
      uses: actions/download-artifact@v4.3.0
      with:
        name: data-artifact
        path: data/
    - name: Use data in job2
      run: cat data/data.txt
  
