name: Publish to GitHub Packages
on:
  push:
    branches: [main]
jobs:
  build_and_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Setup node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 20
      - name: Run install
        run: npm install
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Package the App
        run: npm pack
      - name: Package the App
        uses: actions/upload-artifact@v4.6.2
        with: 
          name: package
          path: "*.tgz"
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: build_and_package
    steps: 
      - name: Download Package
        uses: actions/download-artifact@v5.0.0
        with:
          name: package
      - name: Setup node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@kishorecheryala09'
      - run: echo "registry=https://npm.pkg.github.com/@kishorecheryala09" >> .npmrc
      - run: npm publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      
    
